name: sda_lesson_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  path_provider: ^2.1.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_widget_from_html: ^0.15.1
  html: ^0.15.4 # To parse Bible HTML into clean verses
  flutter_tts: ^3.8.3 # For reading aloud
  shared_preferences: ^2.2.0 # For storing user settings
  flutter_launcher_icons: ^0.13.1
  scrollable_positioned_list: ^0.3.8 # For scrolling to specific verses
  url_launcher: ^6.1.11
  sqflite: ^2.2.0+3
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/hymns.json
    - assets/images/
    - assets/bible.db
    - assets/branding.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # optional
  adaptive_icon_background: "#06275C" # optional (for Android adaptive icons)
  adaptive_icon_foreground: "assets/icon.png" # optional

flutter_native_splash:
  color: "#06275C" # Dark background color
  image: "assets/logo.png" # Using your app icon as the center logo

  # Optional: Different look for Dark Mode
  color_dark: "#06275C"
  image_dark: "assets/logo.png"

  # Android 12+ specific settings
  android_12:
    image: "assets/logo.png"
    icon_background_color: "#06275C"

  android: true
  ios: true
