name: sda_lesson_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  path_provider: ^2.1.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_widget_from_html: ^0.15.1
  share_plus: ^7.2.2
  http: ^1.1.0
  audioplayers: ^5.2.1
  html: ^0.15.4 # To parse Bible HTML into clean verses
  flutter_tts: ^3.8.3 # For reading aloud
  shared_preferences: ^2.2.0 # For storing user settings

  # You can remove flutter_markdown as it isn't needed for this API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    # - assets/hymnals/
    - assets/hymns.json
