name: sda_lesson_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  path_provider: ^2.1.5
  dio: ^5.4.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_widget_from_html: ^0.15.1
  share_plus: ^7.2.2
  http: ^1.1.0
  audioplayers: ^6.0.0
  html: ^0.15.4 
  flutter_tts: ^3.8.3 
  shared_preferences: ^2.5.4 
  flutter_launcher_icons: ^0.13.1
  scrollable_positioned_list: ^0.3.8 
  url_launcher: ^6.1.11
  sqflite: ^2.2.0+3
  font_awesome_flutter: ^10.12.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.2.1
  firebase_storage: ^11.6.5
  firebase_app_distribution: ^1.1.1
  firebase_analytics: ^10.10.7
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.17
  flutter_html: ^3.0.0-beta.2
  flutter_cached_pdfview: ^0.4.2
  
  # Internationalization & Date Formatting
  intl: ^0.20.2

  # Payment Gateways
  mpesa_flutter_plugin: ^1.6.1  
  # flutter_mpesa_stk: ^1.1.0  <-- You can remove this line if you are only using the plugin above

# âœ… CRITICAL FIX: This must be at the ROOT level (No spaces at the start)
# This forces the older mpesa_flutter_plugin to accept your newer intl version
dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    # - assets/hymnals/
    - assets/hymns.json
    - assets/data/hymns_en.json
    - assets/data/hymns_ek.json
    - assets/data/hymns_gk.json
    - assets/data/hymns_lu.json
    - assets/data/hymns_sw.json
    - assets/data/hymns_old_en.json
    - assets/images/
    - assets/json/devotionals/  
    - assets/images/devotionals/
    - assets/bible.db
    - assets/bibles/luo.json
    - assets/bibles/swahili.json
    - assets/bibles/asv.json
    - assets/bibles/gdn.json
    - assets/bibles/nkjv.json
    - assets/bibles/bsb.json
    - assets/bibles/ylt.json
    - assets/bibles/niv.json
    - assets/bibles/amp.json
    - assets/bibles/nasb.json
    - assets/branding.png
    - assets/data/
    - assets/midi/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon.png" 

flutter_native_splash:
  color: "#06275C"
  image: "assets/logo.png"
  color_dark: "#06275C"
  image_dark: "assets/logo.png"
  android_12:
    image: "assets/logo.png"
    icon_background_color: "#06275C"
  android: true
  ios: true